local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base

  update_frequency: 5.0
  publish_frequency: 5.0
  transform_tolerance: 0.5

  # inflation_radius: 1.5
  # cost_scaling_factor: 4.5

  static_map: false
  rolling_window: true
  width: 4
  height: 4
  resolution: 0.05
